# Generated by Django 4.2.30 on 2026-05-15 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRoom',
            fields=[
                ('room_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('host_name', models.CharField(max_length=100)),
                ('host_id', models.CharField(blank=True, max_length=50, null=True)),
                ('room_title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('viewer_count', models.IntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '直播间信息',
                'verbose_name_plural': '直播间信息',
                'db_table': 'live_room',
            },
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('viewer_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(max_length=100)),
                ('fan_level', models.IntegerField(default=0)),
                ('is_followed', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_enter_time', models.DateTimeField(auto_now_add=True)),
                ('last_active_time', models.DateTimeField(auto_now=True)),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='data_screen.liveroom')),
            ],
            options={
                'verbose_name': '观众信息',
                'verbose_name_plural': '观众信息',
                'db_table': 'viewer',
                'indexes': [models.Index(fields=['room_id', 'fan_level'], name='viewer_room_id_28324f_idx')],
            },
        ),
    ]
