# Generated by Django 4.2.30 on 2026-05-15 13:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_screen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveroom',
            name='current_online',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveroom',
            name='total_gifts_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='liveroom',
            name='total_likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('session_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('peak_online', models.IntegerField(default=0)),
                ('total_danmu', models.BigIntegerField(default=0)),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='data_screen.liveroom')),
            ],
            options={
                'verbose_name': '直播场次统计',
                'verbose_name_plural': '直播场次统计',
                'db_table': 'live_session',
                'indexes': [models.Index(fields=['room', 'start_time'], name='live_sessio_room_id_2e6c38_idx')],
            },
        ),
    ]
