# Generated by Django 4.2.30 on 2026-05-16 14:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_screen', '0002_liveroom_current_online_liveroom_total_gifts_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveroom',
            name='room_title',
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开始监控时间'),
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='current_online',
            field=models.IntegerField(default=0, verbose_name='当前在线人数'),
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='host_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主播ID'),
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='host_name',
            field=models.CharField(max_length=100, verbose_name='主播昵称'),
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='是否直播中'),
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='like_count',
            field=models.BigIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='room_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='房间ID'),
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='total_gifts_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='累计礼物价值(元)'),
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='total_likes',
            field=models.BigIntegerField(default=0, verbose_name='累计点赞'),
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='监控结束时间'),
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='viewer_count',
            field=models.IntegerField(default=0, verbose_name='观看人数'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下播时间'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='peak_online',
            field=models.IntegerField(default=0, verbose_name='峰值在线人数'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='room',
            field=models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='data_screen.liveroom', verbose_name='直播间'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='session_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='场次ID'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开播时间'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='total_danmu',
            field=models.BigIntegerField(default=0, verbose_name='弹幕总量'),
        ),
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
