# Generated by Django 4.2.30 on 2026-05-16 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_screen', '0003_remove_liveroom_room_title_alter_liveroom_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveroom',
            name='is_live',
        ),
        migrations.AlterField(
            model_name='livesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='监控结束时间'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='监控开始时间'),
        ),
    ]
