# Generated by Django 4.2.30 on 2026-05-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_screen', '0004_remove_liveroom_is_live_alter_livesession_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveroom',
            name='current_online',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='peak_online',
        ),
    ]
