# Generated by Django 4.2.30 on 2026-05-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_screen', '0005_remove_online_peak_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveroom',
            name='current_online',
            field=models.IntegerField(default=0, verbose_name='当前在线人数'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='peak_online',
            field=models.IntegerField(default=0, verbose_name='峰值在线人数'),
        ),
    ]
